# Generated by Django 5.2.12 on 2026-03-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="thumbnail_path",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
